# Generated by Django 3.2.19 on 2023-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='some@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
