# Generated by Django 3.2.19 on 2023-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-06-12 09:31:19.176709'),
            preserve_default=False,
        ),
    ]
